/* Add objects to this script that should be deleted from ACE-World due to either being duplicates or recreated/regenerated by ACE generators */

/* Duplicates */
DELETE FROM ace_object
WHERE aceObjectId = 3688967941;

DELETE FROM ace_object
WHERE aceObjectId = 2932423033;

DELETE FROM ace_object
WHERE aceObjectId = 3706113473;

DELETE FROM ace_object
WHERE aceObjectId = 3697093316;

DELETE FROM ace_object
WHERE aceObjectId = 3697092699;

DELETE FROM ace_object
WHERE aceObjectId = 2885159582;

DELETE FROM ace_object
WHERE aceObjectId = 2885159323;

DELETE FROM ace_object
WHERE aceObjectId = 3692421382;


/* Regenerated by ACE generators */
DELETE FROM ace_object
WHERE aceObjectId = 2012229714;

DELETE FROM ace_object
WHERE aceObjectId = 2012229730;

DELETE FROM ace_object
WHERE aceObjectId = 2012229709;
