/* Weenie - Armor - Raven Aegis (31395) */
DELETE FROM ace_weenie_class WHERE weenieClassId = 31395;

INSERT INTO ace_weenie_class (`weenieClassId`, `weenieClassDescription`)
VALUES (31395, 'ace31395-ravenaegis');

INSERT INTO `ace_object` (`aceObjectId`, `aceObjectDescriptionFlags`, `weenieClassId`, `weenieHeaderFlags`, `weenieHeaderFlags2`, `currentMotionState`, `physicsDescriptionFlag`)
VALUES (31395, 18, 31395, 270762640, NULL, NULL, 38945);

INSERT INTO `ace_object_properties_string` (`aceObjectId`, `strPropertyId`, `propertyValue`)
VALUES (31395, 1, 'Raven Aegis') /* NAME_STRING */;

INSERT INTO `ace_object_properties_did` (`aceObjectId`, `didPropertyId`, `propertyValue`)
VALUES (31395, 8, 100687958) /* ICON_DID */
     , (31395, 1, 33559617) /* SETUP_DID */
     , (31395, 3, 536870932) /* SOUND_TABLE_DID */
     , (31395, 22, 872415275) /* PHYSICS_EFFECT_TABLE_DID */;

INSERT INTO `ace_object_properties_int` (`aceObjectId`, `intPropertyId`, `propertyValue`)
VALUES (31395, 1, 2) /* ITEM_TYPE_INT */
     , (31395, 5, 600) /* ENCUMB_VAL_INT */
     , (31395, 51, 4) /* COMBAT_USE_INT */
     , (31395, 18, 32) /* UI_EFFECTS_INT */
     , (31395, 151, 2) /* HOOK_TYPE_INT */
     , (31395, 16, 1) /* ITEM_USEABLE_INT */
     , (31395, 9, 2097152) /* LOCATIONS_INT */
     , (31395, 52, 3) /* PARENT_LOCATION_INT */
     , (31395, 93, 1044) /* PHYSICS_STATE_INT */
     , (31395, 9007, 2) /* Clothing_WeenieType */;

INSERT INTO `ace_object_properties_bool` (`aceObjectId`, `boolPropertyId`, `propertyValue`)
VALUES (31395, 13, True) /* ETHEREAL_BOOL */
     , (31395, 11, True) /* IGNORE_COLLISIONS_BOOL */
     , (31395, 14, True) /* GRAVITY_STATUS_BOOL */
     , (31395, 19, True) /* ATTACKABLE_BOOL */
     , (31395, 22, True) /* INSCRIBABLE_BOOL */;

/* Extended Appraisal Data */

REPLACE INTO `ace_object_properties_string` (`aceObjectId`, `strPropertyId`, `propertyValue`)
VALUES (31395, 16, 'A magically imbued Aegis crafted by the Order of the Raven Hand.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LONG_DESC_STRING */;

REPLACE INTO `ace_object_properties_int` (`aceObjectId`, `intPropertyId`, `propertyValue`)
VALUES (31395, 160, 100) /* WIELD_DIFFICULTY_INT */
     , (31395, 176, 6) /* APPRAISAL_ITEM_SKILL_INT */
     , (31395, 33, 1) /* BONDED_INT */
     , (31395, 114, 0) /* ATTUNED_INT */
     , (31395, 115, 400) /* ITEM_SKILL_LEVEL_LIMIT_INT */
     , (31395, 179, 536870912) /* IMBUED_EFFECT_INT */
     , (31395, 19, 0) /* VALUE_INT */
     , (31395, 36, 9999) /* RESIST_MAGIC_INT */
     , (31395, 5, 600) /* ENCUMB_VAL_INT */
     , (31395, 106, 350) /* ITEM_SPELLCRAFT_INT */
     , (31395, 108, 3000) /* ITEM_MAX_MANA_INT */
     , (31395, 28, 0) /* ARMOR_LEVEL_INT */
     , (31395, 158, 7) /* WIELD_REQUIREMENTS_INT */
     , (31395, 159, 1) /* WIELD_SKILLTYPE_INT */;

REPLACE INTO `ace_object_properties_double` (`aceObjectId`, `dblPropertyId`, `propertyValue`)
VALUES (31395, 5, -0.025) /* MANA_RATE_FLOAT */
     , (31395, 159, 1) /* ABSORB_MAGIC_DAMAGE_FLOAT */
     , (31395, 13, 0) /* ARMOR_MOD_VS_SLASH_FLOAT */
     , (31395, 14, 0) /* ARMOR_MOD_VS_PIERCE_FLOAT */
     , (31395, 15, 0) /* ARMOR_MOD_VS_BLUDGEON_FLOAT */
     , (31395, 16, 0) /* ARMOR_MOD_VS_COLD_FLOAT */
     , (31395, 17, 0) /* ARMOR_MOD_VS_FIRE_FLOAT */
     , (31395, 18, 0) /* ARMOR_MOD_VS_ACID_FLOAT */
     , (31395, 19, 0) /* ARMOR_MOD_VS_ELECTRIC_FLOAT */
     , (31395, 165, 1) /* ARMOR_MOD_VS_NETHER_FLOAT */;

REPLACE INTO `ace_object_properties_bool` (`aceObjectId`, `boolPropertyId`, `propertyValue`)
VALUES (31395, 69, 0) /* IS_SELLABLE_BOOL */
     , (31395, 85, 1) /* APPRAISAL_HAS_ALLOWED_WIELDER_BOOL */;

REPLACE INTO `ace_object_properties_spell` (`aceObjectId`, `spellId`)
VALUES (31395, 3819) /* ConscriptsMight_SpellID */
     , (31395, 3820) /* ConscriptsWard_SpellID */
     , (31395, 249) /* InvulnerabilitySelf6_SpellID */;

