DELETE FROM `weenie` WHERE `class_Id` = 23357;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (23357, 'shieldsanguinarygreen', 2, '2019-02-10 07:19:52') /* Clothing */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (23357,   1,          2) /* ItemType - Armor */
     , (23357,   5,        600) /* EncumbranceVal */
     , (23357,   9,    2097152) /* ValidLocations - Shield */
     , (23357,  10,    2097152) /* CurrentWieldedLocation - Shield */
     , (23357,  16,          1) /* ItemUseable - No */
     , (23357,  19,          0) /* Value */
     , (23357,  28,          0) /* ArmorLevel */
     , (23357,  33,          1) /* Bonded - Bonded */
     , (23357,  36,       9999) /* ResistMagic */
     , (23357,  51,          4) /* CombatUse - Shield */
     , (23357,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (23357, 114,          0) /* Attuned - Normal */
     , (23357, 151,          2) /* HookType - Wall */
     , (23357, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (23357,   1, False) /* Stuck */
     , (23357,  11, True ) /* IgnoreCollisions */
     , (23357,  13, True ) /* Ethereal */
     , (23357,  14, True ) /* GravityStatus */
     , (23357,  19, True ) /* Attackable */
     , (23357,  22, True ) /* Inscribable */
     , (23357,  69, False) /* IsSellable */
     , (23357,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (23357,  13,       0) /* ArmorModVsSlash */
     , (23357,  14,       0) /* ArmorModVsPierce */
     , (23357,  15,       0) /* ArmorModVsBludgeon */
     , (23357,  16,       0) /* ArmorModVsCold */
     , (23357,  17,       0) /* ArmorModVsFire */
     , (23357,  18,       0) /* ArmorModVsAcid */
     , (23357,  19,       0) /* ArmorModVsElectric */
     , (23357, 159,       1) /* AbsorbMagicDamage */
     , (23357, 165,       1) /* ArmorModVsNether */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (23357,   1, 'Sanguinary Aegis') /* Name */
     , (23357,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (23357,  25, 'Love''s Blindfold') /* CraftsmanName */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (23357,   1,   33555832) /* Setup */
     , (23357,   3,  536870932) /* SoundTable */
     , (23357,   6,   67111919) /* PaletteBase */
     , (23357,   8,  100669659) /* Icon */
     , (23357,  22,  872415275) /* PhysicsEffectTable */
     , (23357, 8001,  270762512) /* PCAPRecordedWeenieHeader - Usable, CombatUse, Wielder, ValidLocations, CurrentlyWieldedLocation, Burden, HookType */
     , (23357, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (23357, 8005,      38945) /* PCAPRecordedPhysicsDesc - CSetup, Parent, STable, PeTable, Position */
     , (23357, 8009,          3) /* PCAPRecordedParentLocation - Shield */;

INSERT INTO `weenie_properties_position` (`object_Id`, `position_Type`, `obj_Cell_Id`, `origin_X`, `origin_Y`, `origin_Z`, `angles_W`, `angles_X`, `angles_Y`, `angles_Z`)
VALUES (23357, 8040, 4135714858, 143.0369, 47.3806, 57.7198, 0.5302896, 0.2738894, -0.7968491, 0.09385709) /* PCAPRecordedLocation */
/* @teleloc 0xF682002A [143.036900 47.380600 57.719800] 0.530290 0.273889 -0.796849 0.093857 */;

INSERT INTO `weenie_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (23357, 8000, 2778182479) /* PCAPRecordedObjectIID */
     , (23357, 8008, 1343460302) /* PCAPRecordedParentIID */;

INSERT INTO `weenie_properties_palette` (`object_Id`, `sub_Palette_Id`, `offset`, `length`)
VALUES (23357, 67111923, 0, 0);

INSERT INTO `weenie_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`)
VALUES (23357, 0, 83890137, 83890137)
     , (23357, 0, 83889688, 83889688);

INSERT INTO `weenie_properties_anim_part` (`object_Id`, `index`, `animation_Id`)
VALUES (23357, 0, 16782688);
