DELETE FROM `weenie` WHERE `class_Id` = 23360;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`)
VALUES (23360, 'shieldsanguinarywhite', 2) /* Clothing */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (23360,   1,          2) /* ItemType - Armor */
     , (23360,   5,        600) /* EncumbranceVal */
     , (23360,   9,    2097152) /* ValidLocations - Shield */
     , (23360,  16,          1) /* ItemUseable - No */
     , (23360,  19,          0) /* Value */
     , (23360,  28,          0) /* ArmorLevel */
     , (23360,  33,          1) /* Bonded - Bonded */
     , (23360,  36,       9999) /* ResistMagic */
     , (23360,  51,          4) /* CombatUse - Shield */
     , (23360,  65,        101) /* Placement - Resting */
     , (23360,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (23360, 114,          0) /* Attuned - Normal */
     , (23360, 151,          2) /* HookType - Wall */
     , (23360, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (23360,   1, False) /* Stuck */
     , (23360,  11, True ) /* IgnoreCollisions */
     , (23360,  13, True ) /* Ethereal */
     , (23360,  14, True ) /* GravityStatus */
     , (23360,  19, True ) /* Attackable */
     , (23360,  22, True ) /* Inscribable */
     , (23360,  69, False) /* IsSellable */
     , (23360,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (23360,  13,       0) /* ArmorModVsSlash */
     , (23360,  14,       0) /* ArmorModVsPierce */
     , (23360,  15,       0) /* ArmorModVsBludgeon */
     , (23360,  16,       0) /* ArmorModVsCold */
     , (23360,  17,       0) /* ArmorModVsFire */
     , (23360,  18,       0) /* ArmorModVsAcid */
     , (23360,  19,       0) /* ArmorModVsElectric */
     , (23360, 159,       1) /* AbsorbMagicDamage */
     , (23360, 165,       1) /* ArmorModVsNether */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (23360,   1, 'Sanguinary Aegis') /* Name */
     , (23360,   7, 'Former Advocate Ripley') /* Inscription */
     , (23360,   8, 'Ripley') /* ScribeName */
     , (23360,  16, 'A crystalline barrier infused with the magical properties of distilled chorizite.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (23360,  25, 'Ripley') /* CraftsmanName */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (23360,   1,   33555836) /* Setup */
     , (23360,   3,  536870932) /* SoundTable */
     , (23360,   6,   67111919) /* PaletteBase */
     , (23360,   8,  100669654) /* Icon */
     , (23360,  22,  872415275) /* PhysicsEffectTable */
     , (23360, 8001,  270615056) /* PCAPRecordedWeenieHeader - Usable, CombatUse, Container, ValidLocations, Burden, HookType */
     , (23360, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (23360, 8005,     137217) /* PCAPRecordedPhysicsDesc - CSetup, STable, PeTable, AnimationFrame */;

INSERT INTO `weenie_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (23360,   2, 2186220426) /* Container */
     , (23360, 8000, 2151959813) /* PCAPRecordedObjectIID */;

INSERT INTO `weenie_properties_palette` (`object_Id`, `sub_Palette_Id`, `offset`, `length`)
VALUES (23360, 67111920, 0, 0);

INSERT INTO `weenie_properties_texture_map` (`object_Id`, `index`, `old_Id`, `new_Id`)
VALUES (23360, 0, 83890137, 83890137)
     , (23360, 0, 83889688, 83889688);

INSERT INTO `weenie_properties_anim_part` (`object_Id`, `index`, `animation_Id`)
VALUES (23360, 0, 16782688);
