DELETE FROM `weenie` WHERE `class_Id` = 31395;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (31395, 'ace31395-ravenaegis', 2, '2019-02-10 05:41:14') /* Clothing */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (31395,   1,          2) /* ItemType - Armor */
     , (31395,   5,        600) /* EncumbranceVal */
     , (31395,   9,    2097152) /* ValidLocations - Shield */
     , (31395,  10,    2097152) /* CurrentWieldedLocation - Shield */
     , (31395,  16,          1) /* ItemUseable - No */
     , (31395,  18,         32) /* UiEffects - Fire */
     , (31395,  19,          0) /* Value */
     , (31395,  28,          0) /* ArmorLevel */
     , (31395,  33,          1) /* Bonded - Bonded */
     , (31395,  36,       9999) /* ResistMagic */
     , (31395,  51,          4) /* CombatUse - Shield */
     , (31395,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (31395, 106,        350) /* ItemSpellcraft */
     , (31395, 107,       2765) /* ItemCurMana */
     , (31395, 108,       3000) /* ItemMaxMana */
     , (31395, 114,          0) /* Attuned - Normal */
     , (31395, 115,        400) /* ItemSkillLevelLimit */
     , (31395, 151,          2) /* HookType - Wall */
     , (31395, 158,          7) /* WieldRequirements - Level */
     , (31395, 159,          1) /* WieldSkillType - Axe */
     , (31395, 160,        100) /* WieldDifficulty */
     , (31395, 176,          6) /* AppraisalItemSkill */
     , (31395, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (31395,   1, False) /* Stuck */
     , (31395,  11, True ) /* IgnoreCollisions */
     , (31395,  13, True ) /* Ethereal */
     , (31395,  14, True ) /* GravityStatus */
     , (31395,  19, True ) /* Attackable */
     , (31395,  22, True ) /* Inscribable */
     , (31395,  69, False) /* IsSellable */
     , (31395,  85, True ) /* AppraisalHasAllowedWielder */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (31395,   5,  -0.025) /* ManaRate */
     , (31395,  13,       0) /* ArmorModVsSlash */
     , (31395,  14,       0) /* ArmorModVsPierce */
     , (31395,  15,       0) /* ArmorModVsBludgeon */
     , (31395,  16,       0) /* ArmorModVsCold */
     , (31395,  17,       0) /* ArmorModVsFire */
     , (31395,  18,       0) /* ArmorModVsAcid */
     , (31395,  19,       0) /* ArmorModVsElectric */
     , (31395, 159,       1) /* AbsorbMagicDamage */
     , (31395, 165,       1) /* ArmorModVsNether */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (31395,   1, 'Raven Aegis') /* Name */
     , (31395,  16, 'A magically imbued Aegis crafted by the Order of the Raven Hand.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */
     , (31395,  25, 'Callaway') /* CraftsmanName */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (31395,   1,   33559617) /* Setup */
     , (31395,   3,  536870932) /* SoundTable */
     , (31395,   8,  100687958) /* Icon */
     , (31395,  22,  872415275) /* PhysicsEffectTable */
     , (31395, 8001,  270762640) /* PCAPRecordedWeenieHeader - Usable, UiEffects, CombatUse, Wielder, ValidLocations, CurrentlyWieldedLocation, Burden, HookType */
     , (31395, 8003,         18) /* PCAPRecordedObjectDesc - Inscribable, Attackable */
     , (31395, 8005,      38945) /* PCAPRecordedPhysicsDesc - CSetup, Parent, STable, PeTable, Position */
     , (31395, 8009,          3) /* PCAPRecordedParentLocation - Shield */;

INSERT INTO `weenie_properties_position` (`object_Id`, `position_Type`, `obj_Cell_Id`, `origin_X`, `origin_Y`, `origin_Z`, `angles_W`, `angles_X`, `angles_Y`, `angles_Z`)
VALUES (31395, 8040, 2847146012, 73.45782, 81.92619, 78.51093, -0.2575725, 0.6684368, 0.5130069, 0.4729404) /* PCAPRecordedLocation */
/* @teleloc 0xA9B4001C [73.457820 81.926190 78.510930] -0.257573 0.668437 0.513007 0.472940 */;

INSERT INTO `weenie_properties_i_i_d` (`object_Id`, `type`, `value`)
VALUES (31395, 8000, 3620339638) /* PCAPRecordedObjectIID */
     , (31395, 8008, 1343282139) /* PCAPRecordedParentIID */;

INSERT INTO `weenie_properties_spell_book` (`object_Id`, `spell`, `probability`)
VALUES (31395,   249,      2) 
     , (31395,  3819,      2) 
     , (31395,  3820,      2) ;
